language: ruby
cache: bundler
rvm:
- 2.4

env:
  secure: Xzjhm72VbFnlXl9j705/TTrMudaTAp1VPH7aMR2TypzhDodw0239lBXXSO5ibhxc/LAMFx9miBnUaprJQtO9ytBP0evWI+JFtzQsoGreaYf37bX1uU52Y383yw3cmon5q40/yrVAWVYmqKrkzgUj6LjdWgwVSPMGkypL5YPifbLkKwSyPGtUUFu8Pyc9dkLW8vby5GfuYqTv12AHuwH3A8DXv6GzFyj5aGnQsFuy0SPLesziRcGd362zrq6IRdgnh7FiBVGx0sjtX3XbWzauHrFlLiJ5RF3DqoORxYPowy1LOlyccgEBtB4y5WVE0e048ZH9ey551fz1vF38B6m3JvLcz8VIkVxob+0TZAeAXh2m2pb5atmuG5Jpz9qWvBPCHjCyt7hEagiIVpz5bM8QZu+Xml6mniOvk/mXgOEJXPCxUwVDgE8/pMEs9nkk9mQ/4CYhU9usbwHzo/3Se3GhfojrGd8I+8GqylmU+k3BPphofDN7ccxgEbMY8arQoLy5UdBvSt+HJqaQ73W998A/C6QcX4mPQIpg8J5ep9nPjFzP/ViZz6t+RrSTWVp+xVZylEeDd9LktyjlSprJGdmOgnyaoXYm4n5gg6Y3wj3yeIYy/uzzixDGh4gBtMAWPn+6IVa+ICPn088BcyNQLZaz0W+VKxEbL7CKa6B1YQNnMGQ=

install:
  # https://github.com/travis-ci/dpl/issues/574
  - yes y | gem uninstall gems
  - yes y | gem uninstall dpl
  - gem install gems -v 0.8.3
  - gem install dpl -v 1.8.27
  - bundle install

jobs:
  include:
    - stage: deploy
      if: env(TRAVIS_TAG) IS present
      rvm: 2.4
      script: ./scripts/deploy.sh
